# ------------------------------------------------------------------------------
# String templates for C documents
#

from string import Template

C_HEADER_TEMPLATE = Template("""
// Header for module '${json_module_name}'
// automatically generated by HDLRegs version $hdlregs_version on $date_time

#ifndef ${module_name}_H
#define ${module_name}_H

//
// Register address offsets
//
$address_offsets
$fields
#endif // ${module_name}_H
""")
